
export const ITEMS_HAS_ERRORED = "ITEMS_HAS_ERRORED";

export const ITEMS_IS_LOADING = "ITEMS_IS_LOADING";

export const ITEMS_FETCH_DATA_SUCCESS = "ITEMS_FETCH_DATA_SUCCESS";

export const SET_CURRENT_URL = "SET_CURRENT_URL";

export const IS_USER_LOGGED_IN = "IS_USER_LOGGED_IN";

export const ADD_EVENT = "ADD_EVENT";

export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';

export const PASSWORD_CHANGE_RETYPE = 'PASSWORD_CHANGE_RETYPE';
