
export const ADD_EVENT = "ADD_EVENT";

export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';

export const PASSWORD_CHANGE_RETYPE = 'PASSWORD_CHANGE_RETYPE';

export const SIGN_USER = 'SIGN_USER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const USER_PROFILE = 'USER_PROFILE';

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
